### ISSUE TITLE
The link to the paper no longer works

### ISSUE THREAD

**Issue by Codeguyross** [fwilliams/surface-reconstruction-benchmark#1]
Hello,

The link to the publication no longer works. I suggest updating to something like: http://vgc.poly.edu/files/berger/recon_bench/paper/tog.pdf

**Comment by fwilliams** [comment]
Hey thanks for pointing this out! I wish all papers were on arXiv and we wouldn't have this problem.

**Comment by fwilliams** [comment]
Okay I updated the link now. Thanks again!
